---
name: Build and test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [ecmp-manager]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Build and start image
      - name: Build and start image
        run: |
          docker compose up --build --detach
          docker compose exec ecmp-manager \
            'apt-get update && apt-get --no-install-recommends --yes install iputils-ping && ping -c 5 1.1.1.1'
      # Wait for container to start and run
      - name: Wait for container to start and run
        run: |
          sleep 60
      # Grab the container logs
      - name: Grab container logs
        run: |
          docker compose logs ecmp-manager
      # Stop and remove containers
      - name: Stop and remove container
        run: |
          docker compose down
